Update French Translation
jlucidar/fpv_viewer_android pull request #95
Opened 2021-08-11 07:45 UTC by grenagit

2021-08-17 02:12 UTC, fichek requested changes

2021-08-17 02:12 UTC, fichek commented on app/src/main/res/values-fr/strings.xml
> +    <string name="waiting_f    <string name="digiview_feed">DigiView\nflux</string>
Error here.

2021-08-18 23:34 UTC, fichek submitted a review, later dismissed

2021-08-18 23:34 UTC, fichek commented on app/src/main/res/values-fr/strings.xml
> +</resources>>
Double closing `>`

2021-08-27 13:40 UTC, trigger7 commented
I had a quick look through grenagit's translation, looks good to me.
Much more faithful to the English strings than the previous ones.

2021-11-22 17:00 UTC, merged

2021-11-22 17:03 UTC, jlucidar commented
Sorry for the delay. I just did a minor fix to replace "Analytiques" which sounded weird. (I'm french btw )
I sort of hesitated to merge this because the translations were already ok, but they are now closest to the english reference.

Thanks for the PR !